export const OPENINGS: Record<string, string> = {
  // e4 openings
  'e4': "King's Pawn",
  'e4 c5': 'Sicilian Defence',
  'e4 c5 Nf3': 'Sicilian Defence',
  'e4 c5 Nf3 d6': 'Sicilian Defence',
  'e4 c5 Nf3 d6 d4': 'Sicilian Defence',
  'e4 c5 Nf3 d6 d4 cxd4': 'Sicilian Defence',
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4': 'Sicilian Defence',
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6': 'Sicilian Defence',
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3': 'Sicilian Defence',
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6': 'Sicilian, Najdorf Variation',
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6': 'Sicilian, Dragon Variation',
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nc6': 'Sicilian, Classical Variation',
  'e4 c5 Nf3 e6': 'Sicilian Defence',
  'e4 c5 Nf3 Nc6': 'Sicilian Defence',
  'e4 c5 Nf3 Nc6 d4': 'Sicilian Defence',
  'e4 c5 Nf3 Nc6 d4 cxd4': 'Sicilian Defence',
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4': 'Sicilian Defence',
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 e6': 'Sicilian, Paulsen Variation',
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6': 'Sicilian, Accelerated Dragon',
  'e4 c5 Nc3': 'Sicilian Defence',
  'e4 c5 c3': 'Sicilian, Alapin Variation',
  'e4 c5 b4': 'Sicilian, Wing Gambit',
  'e4 c5 d4': 'Sicilian, Smith-Morra Gambit',

  'e4 e5': 'Open Game',
  'e4 e5 Nf3': "King's Knight Opening",
  'e4 e5 Nf3 Nc6': 'Three Knights Opening',
  'e4 e5 Nf3 Nc6 Bb5': 'Ruy Lopez',
  'e4 e5 Nf3 Nc6 Bb5 a6': 'Ruy Lopez, Morphy Defence',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4': 'Ruy Lopez, Morphy Defence',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6': 'Ruy Lopez, Open Defence',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O': 'Ruy Lopez, Main Line',
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7': 'Ruy Lopez, Closed Variation',
  'e4 e5 Nf3 Nc6 Bb5 Nf6': 'Ruy Lopez, Berlin Defence',
  'e4 e5 Nf3 Nc6 Bb5 Bc5': 'Ruy Lopez, Classical Defence',
  'e4 e5 Nf3 Nc6 Bc4': 'Italian Game',
  'e4 e5 Nf3 Nc6 Bc4 Bc5': 'Italian Game, Giuoco Piano',
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3': 'Italian Game, Giuoco Pianissimo',
  'e4 e5 Nf3 Nc6 Bc4 Nf6': 'Italian Game, Two Knights Defence',
  'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5': 'Italian Game, Two Knights, Ng5',
  'e4 e5 Nf3 Nc6 d4': 'Scotch Game',
  'e4 e5 Nf3 Nc6 d4 exd4': 'Scotch Game',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4': 'Scotch Game',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6': 'Scotch Four Knights',
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5': 'Scotch Game, Classical Variation',
  'e4 e5 Nf3 Nf6': "Petrov's Defence",
  'e4 e5 Nf3 Nf6 Nxe5': "Petrov's Defence",
  'e4 e5 Nf3 Nf6 Nc3': 'Four Knights Game',
  'e4 e5 f4': "King's Gambit",
  'e4 e5 f4 exf4': "King's Gambit Accepted",
  'e4 e5 f4 exf4 Nf3': "King's Gambit Accepted",
  'e4 e5 f4 d5': 'Falkbeer Counter-Gambit',
  'e4 e5 Nc3': 'Vienna Game',
  'e4 e5 Nc3 Nf6': 'Vienna Game',
  'e4 e5 d4': 'Centre Game',
  'e4 e5 d4 exd4': 'Centre Game',
  'e4 e5 Bc4': "Bishop's Opening",

  'e4 e6': 'French Defence',
  'e4 e6 d4': 'French Defence',
  'e4 e6 d4 d5': 'French Defence',
  'e4 e6 d4 d5 Nc3': 'French, Classical Variation',
  'e4 e6 d4 d5 Nc3 Nf6': 'French, Classical Variation',
  'e4 e6 d4 d5 Nc3 Bb4': 'French, Winawer Variation',
  'e4 e6 d4 d5 e5': 'French, Advance Variation',
  'e4 e6 d4 d5 e5 c5': 'French, Advance, Main Line',
  'e4 e6 d4 d5 exd5': 'French, Exchange Variation',
  'e4 e6 d4 d5 Nd2': 'French, Tarrasch Variation',
  'e4 e6 d4 d5 Nd2 Nf6': 'French, Tarrasch Variation',
  'e4 e6 d4 d5 Nd2 c5': 'French, Tarrasch, Open Variation',

  'e4 c6': 'Caro-Kann Defence',
  'e4 c6 d4': 'Caro-Kann Defence',
  'e4 c6 d4 d5': 'Caro-Kann Defence',
  'e4 c6 d4 d5 Nc3': 'Caro-Kann, Classical Variation',
  'e4 c6 d4 d5 Nc3 dxe4': 'Caro-Kann, Classical Variation',
  'e4 c6 d4 d5 Nc3 dxe4 Nxe4': 'Caro-Kann, Classical Variation',
  'e4 c6 d4 d5 e5': 'Caro-Kann, Advance Variation',
  'e4 c6 d4 d5 exd5': 'Caro-Kann, Exchange Variation',
  'e4 c6 d4 d5 Nd2': 'Caro-Kann, Tartakower Variation',

  'e4 d5': 'Scandinavian Defence',
  'e4 d5 exd5': 'Scandinavian Defence',
  'e4 d5 exd5 Qxd5': 'Scandinavian, Main Line',
  'e4 d5 exd5 Qxd5 Nc3': 'Scandinavian, Main Line',
  'e4 d5 exd5 Nf6': 'Scandinavian, Icelandic Gambit',

  'e4 d6': "Pirc Defence",
  'e4 d6 d4': "Pirc Defence",
  'e4 d6 d4 Nf6': "Pirc Defence",
  'e4 d6 d4 Nf6 Nc3': "Pirc Defence",
  'e4 d6 d4 Nf6 Nc3 g6': "Pirc Defence",

  'e4 Nf6': "Alekhine's Defence",
  'e4 Nf6 e5': "Alekhine's Defence",
  'e4 Nf6 e5 Nd5': "Alekhine's Defence",

  'e4 g6': 'Modern Defence',
  'e4 g6 d4': 'Modern Defence',
  'e4 g6 d4 Bg7': 'Modern Defence',

  'e4 b6': "Owen's Defence",
  'e4 Nc6': 'Nimzowitsch Defence',

  // d4 openings
  'd4': "Queen's Pawn",
  'd4 d5': "Queen's Pawn Game",
  'd4 d5 c4': "Queen's Gambit",
  'd4 d5 c4 dxc4': "Queen's Gambit Accepted",
  'd4 d5 c4 dxc4 Nf3': "Queen's Gambit Accepted",
  'd4 d5 c4 dxc4 e3': "Queen's Gambit Accepted",
  'd4 d5 c4 e6': "Queen's Gambit Declined",
  'd4 d5 c4 e6 Nc3': "Queen's Gambit Declined",
  'd4 d5 c4 e6 Nc3 Nf6': "Queen's Gambit Declined",
  'd4 d5 c4 e6 Nc3 Nf6 Bg5': "Queen's Gambit Declined, Orthodox",
  'd4 d5 c4 e6 Nf3': "Queen's Gambit Declined",
  'd4 d5 c4 c6': 'Slav Defence',
  'd4 d5 c4 c6 Nf3': 'Slav Defence',
  'd4 d5 c4 c6 Nf3 Nf6': 'Slav Defence',
  'd4 d5 c4 c6 Nf3 Nf6 Nc3': 'Slav Defence',
  'd4 d5 c4 c6 Nc3': 'Slav Defence',
  'd4 d5 c4 Nc6': "Chigorin Defence",
  'd4 d5 Nf3': "Queen's Pawn Game",
  'd4 d5 Nf3 Nf6': 'London System',
  'd4 d5 Nf3 Nf6 Bf4': 'London System',
  'd4 d5 Nf3 Nf6 Bf4 e6': 'London System',
  'd4 d5 Bf4': 'London System',

  'd4 Nf6': "Indian Defence",
  'd4 Nf6 c4': "Indian Defence",
  'd4 Nf6 c4 e6': "Nimzo/Queen's Indian",
  'd4 Nf6 c4 e6 Nc3': 'Nimzo-Indian Defence',
  'd4 Nf6 c4 e6 Nc3 Bb4': 'Nimzo-Indian Defence',
  'd4 Nf6 c4 e6 Nc3 Bb4 e3': 'Nimzo-Indian, Rubinstein Variation',
  'd4 Nf6 c4 e6 Nc3 Bb4 Qc2': 'Nimzo-Indian, Classical Variation',
  'd4 Nf6 c4 e6 Nf3': "Queen's Indian Defence",
  'd4 Nf6 c4 e6 Nf3 b6': "Queen's Indian Defence",
  'd4 Nf6 c4 e6 Nf3 b6 g3': "Queen's Indian, Fianchetto",
  'd4 Nf6 c4 g6': "King's Indian Defence",
  'd4 Nf6 c4 g6 Nc3': "King's Indian Defence",
  'd4 Nf6 c4 g6 Nc3 Bg7': "King's Indian Defence",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4': "King's Indian Defence",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6': "King's Indian Defence",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3': "King's Indian, Classical",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3': "King's Indian, Sämisch",
  'd4 Nf6 c4 c5': 'Benoni Defence',
  'd4 Nf6 c4 c5 d5': 'Modern Benoni',
  'd4 Nf6 c4 c5 d5 e6': 'Modern Benoni',
  'd4 Nf6 Nf3': "Indian Defence",
  'd4 Nf6 Nf3 g6': "King's Indian Attack",
  'd4 Nf6 Nf3 d5': "Queen's Pawn",
  'd4 Nf6 Nf3 e6': "Queen's Pawn",
  'd4 Nf6 Bf4': 'London System',

  'd4 e6': "Indian Defence",
  'd4 f5': 'Dutch Defence',
  'd4 f5 c4': 'Dutch Defence',
  'd4 f5 g3': 'Dutch Defence',
  'd4 g6': 'Modern Defence',

  // c4 openings
  'c4': 'English Opening',
  'c4 e5': 'English Opening',
  'c4 e5 Nc3': 'English Opening',
  'c4 c5': 'English, Symmetrical',
  'c4 Nf6': 'English Opening',
  'c4 e6': 'English Opening',
  'c4 g6': 'English Opening',

  // Nf3 openings
  'Nf3': "Réti Opening",
  'Nf3 d5': "Réti Opening",
  'Nf3 d5 c4': "Réti, Queen's Gambit",
  'Nf3 Nf6': "Réti Opening",
  'Nf3 d5 g3': "Réti, Fianchetto",

  // Other first moves
  'b3': "Larsen's Opening",
  'b4': 'Sokolsky Opening',
  'f4': "Bird's Opening",
  'g3': "King's Fianchetto Opening",
  'g4': 'Grob Attack',
  'a3': "Anderssen's Opening",
  'd3': "King's Indian Attack",
  'Nc3': "Dunst Opening",
};

export function getOpeningName(sanHistory: string[]): string | null {
  for (let len = Math.min(sanHistory.length, 12); len >= 1; len--) {
    const key = sanHistory.slice(0, len).join(' ');
    if (OPENINGS[key]) return OPENINGS[key];
  }
  return null;
}
